server:
  port: 8001
spring:
  application:
    name: spring-login-begin
eureka:
  instance:
    instance-id: springBegin
    prefer-ip-address: false  #是否把服务注册进注册中心
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7002.com:7002/eureka
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000